name: Flutter CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Cài đặt Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3' # hoặc version bạn dùng

      # 3️⃣ Kiểm tra Flutter version
      - name: Flutter version
        run: flutter --version

      # 4️⃣ Get dependencies
      - name: Flutter pub get
        run: flutter pub get

      # 5️⃣ Build APK release
      - name: Build APK
        run: flutter build apk --release

      # 6️⃣ Upload artifact (APK)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
